version: "3.7"
services:
  server:
    image: ebrana-node
    build:
      context: ./docker
      dockerfile: node/Dockerfile
    networks:
      - ebrana_platform_network
    ports:
      - '8001:8001'
    volumes:
      - .:/var/www/html
    entrypoint: ["npm", "run", "start"]
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0.21
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: noderuner
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ebrana_platform_network
    volumes:
      - mongo-db:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  u_npm:
    image: ebrana-node
    build:
      context: ./docker
      dockerfile: node/Dockerfile
    networks:
      - ebrana_platform_network
    volumes:
      - .:/var/www/html
    entrypoint: ["npm"]

networks:
  ebrana_platform_network:

volumes:
  mongo-db: